version: "3"

services:
  database:
    container_name: abz-agency-db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
      - MYSQL_DATABASE="${DATABASE}"
      - MYSQL_USER="${DB_USERNAME}"
      - MYSQL_PASSWORD="${DB_PASSWORD}"
    volumes:
      - mysql:/var/lib/mysql
    restart: always

  server:
    container_name: server
    image: dovhanrg/abz-server:latest
    restart: always
    environment:
      - NODE_ENV="$NODE_ENV"
      - IP_ADDR="$IP_ADDR"
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USERNAME="$DB_USERNAME"
      - DB_PASSWORD="$DB_PASSWORD"
      - DATABASE="$DATABASE"
    ports:
      - "4000:4000"
    volumes:
      - ../server/seeds:/app/data/uploads
    depends_on:
      - database

  client:
    container_name: client
    image: dovhanrg/abz-client:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV="$NODE_ENV"
    depends_on:
      - server

volumes:
  mysql:
  uploads:
