CREATE DATABASE IF NOT EXISTS `abz-agency`;
CREATE USER 'admin'@'%' IDENTIFIED BY 'admin';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `abz-agency`.* TO 'admin'@'%';

FLUSH PRIVILEGES;