version: "3"

services:
  mysql:
    container_name: abz-agency-db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=abz-agency
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/setup.sql
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql: