name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-server:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: dovhanrg/abz-server
          tags: latest, ${{ github.sha }}
          registry: docker.io
          dockerfile: ./server/Dockerfile
          directory: ./server/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#          buildArgs: NODE_ENV=${{ secrets.NODE_ENV }}, IP_ADDR=${{ secrets.IP_ADDR }}, DB_HOST=${{ secrets.DB_HOST }}, DB_PORT=3306, DB_USERNAME=${{ secrets.DB_USERNAME }}, DB_PASSWORD=${{ secrets.DB_PASSWORD }}, DATABASE=${{ secrets.DATABASE }}

  build-client:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: dovhanrg/abz-client
          tags: latest, ${{ github.sha }}
          registry: docker.io
          dockerfile: ./client/Dockerfile
          directory: ./client/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
